excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jacobopus.github.io
title: ajedrezescolar
tagline: Ajedrez en las escuelas, los hogares y las calles
description: Actividades y talleres de clubes de ajedrez formados por coach Jacobopus
paginate: 5